[2020-11-01 23:26:32,102] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: S3_task.upload_file_to_S3 2020-11-01T21:00:00+00:00 [queued]>
[2020-11-01 23:26:32,174] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: S3_task.upload_file_to_S3 2020-11-01T21:00:00+00:00 [queued]>
[2020-11-01 23:26:32,175] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-11-01 23:26:32,175] {taskinstance.py:881} INFO - Starting attempt 1 of 4
[2020-11-01 23:26:32,175] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-11-01 23:26:32,206] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): upload_file_to_S3> on 2020-11-01T21:00:00+00:00
[2020-11-01 23:26:32,221] {standard_task_runner.py:54} INFO - Started process 2003 to run task
[2020-11-01 23:26:32,336] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'S3_task', 'upload_file_to_S3', '2020-11-01T21:00:00+00:00', '--job_id', '128', '--pool', 'default_pool', '--raw', '-sd', '/home/akorede/Documents/airflow_sandbox/airflow/dags/s3_dag.py', '--cfg_path', '/tmp/tmplew_jzyq']
[2020-11-01 23:26:32,340] {standard_task_runner.py:78} INFO - Job 128: Subtask upload_file_to_S3
[2020-11-01 23:26:32,438] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: S3_task.upload_file_to_S3 2020-11-01T21:00:00+00:00 [running]> akorede-VirtualBox
[2020-11-01 23:26:34,534] {taskinstance.py:1150} ERROR - name 'json_buffer' is not defined
Traceback (most recent call last):
  File "/home/akorede/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/akorede/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/akorede/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/akorede/Documents/airflow_sandbox/airflow/dags/s3_dag.py", line 66, in upload_file_to_S3_with_hook
    json_buffer.seek(0)
NameError: name 'json_buffer' is not defined
[2020-11-01 23:26:34,536] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=S3_task, task_id=upload_file_to_S3, execution_date=20201101T210000, start_date=20201101T222632, end_date=20201101T222634
[2020-11-01 23:26:37,077] {local_task_job.py:102} INFO - Task exited with return code 1
